project:
  type: book
  output-dir: _book

book:
  title: "Análise do Cumprimento das Metas de Redução de Mortes no Trânsito dos Municípios Brasileiros até 2023."
  author: 
  - name: Ana Beatriz da S. Marques
    orcid: 0009-0005-0639-8325
  - name: Dr. Jorge Tiago Bastos
    orcid: 0000-0001-6447-1504
  date: 2025/07/27
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - results.qmd
    - conclusion.qmd
    - references.qmd

format:
  html:
    css: styles.css
    theme: cosmo
  pdf:
    documentclass: book
website:
  repo-url: https://github.com/betrizmarques/relatorio-cumprimento-metas.git
  repo-actions: [edit, issue]